### ISSUE TITLE
standalone 실행파일이 필요합니다.

### ISSUE THREAD

**Issue by ryusatgat** [VINTO1819/Garam-Interpreter#2]
https://www.ryugod.com/pages/개발환경/garam 위치에 온라인 인터프리터 환경을 만들었습니다.

차후에 코드 수정이 있을 때 바로 적용해볼 수 있도록 단일 실행 파일을 요청드립니다.

ps) 허락없이 온라인 IDE를 만들어서 죄송합니다. 혹여나 불편하시다면 바로 내리도록 하겠습니다.

**Comment by ericlee05** [comment]
안녕하세요, 이런 보잘것 없는 언어를 IDE에 추가해주셔서 감사합니다 ㅜㅜ
혹시 말씀하시는 standalone 파일이 어떤 것을 의미하시는지 말씀해 주실 수 있을까요?

**Comment by ryusatgat** [comment]
npm -g install yarn 을 하면 yarn 명령을 쓸 수 있습니다.
마찬가지로 npm -g garam-interpreter로 설치하면 garam 명령으로 인터프리팅이 되면 좋겠습니다. 지금은 제가 임의로 소스를 고쳐서 실행되게 만들어놨습니다.

**Comment by ericlee05** [comment]
그렇다면 혹시 jar 파일 형식으로 만들어드려도 될까요?
Node.js 버전으로는 standalone을 지원하자니 여건 상 어려워서 Kotlin으로 개발해야 할 거 같아서요

**Comment by ryusatgat** [comment]
괜찮습니다. 재개발까지는 필요없을거 같습니다. 나중에 수정이 생기면 제가 알아서 적용할게요. 감사합니다.
